spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: students
          url: http;//localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: school
          url: http;//localhost:8080
          predicates:
            - Path=/api/v1/school/**
management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

