eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: student
  jpa:
    generate-ddl: true
server:
  port: 8090
  servlet:
    context-path: "/api"

management:
  tracing:
    sampling:
      probability: 1.0