spring:
  application:
    name: student
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    generate-ddl: true
server:
  port: 8090
  servlet:
    context-path: "/api"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
